server:
  port: 8911

spring:
  cloud:
    gateway:
      routes:
        - id: hello_api
          uri: http://localhost:8081
          predicates:
            - Path=/v1/api/hello/**
#          filters:
#            - StripPrefix=1

        - id: service2_route
          uri: http://localhost:8082
          predicates:
            - Path=/service2/**

logging:
  level:
    io.netty: DEBUG