server:
  port: 8911

spring:
  application:
    name: gateway-service
  sleuth:
    trace-id128: true # 128-битный traceId
    supports-join: true
#  sleuth:
#    sampler:
#      probability: 1.0
#    zipkin:
#      base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: public-auth_java_api
          uri: http://localhost:8079
          predicates:
            - Path=/v1/api/auth/login

        - id: private_hello_api
          uri: http://localhost:8081
          predicates:
            - Path=/v1/api/hello/**
      default-filters:
        - AuthFilter

#management:
#  tracing:
#    enabled: true

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0 # Обязательно для генерации traceId
    propagation:
      type: W3C # Используем современный формат

#  Более специфичные пути должны быть указаны раньше в списке.
security:
  public-paths:
    - /v1/api/auth/login
#    - /v1/api/public/**  # Все подпути
#    - /v2/api/docs/*.html  # Конкретные файлы

  role-paths:
    - path: /v1/api/hello
      roles: [USER, ADMIN]
#    - path: /v1/api/profile  # Доступно всем аутентифицированным
#      roles: [ ]

logging:
  level:
    io.netty: DEBUG