server:
  port: 8911

spring:
  cloud:
    gateway:
      routes:
        - id: public-auth_java_api
          uri: http://localhost:8079
          predicates:
            - Path=/v1/api/auth/login

        - id: private_hello_api
          uri: http://localhost:8081
          predicates:
            - Path=/v1/api/hello/**
      default-filters:
        - AuthFilter

#  Более специфичные пути должны быть указаны раньше в списке.
security:
  public-paths:
    - /v1/api/auth/login
#    - /v1/api/public/**  # Все подпути
#    - /v2/api/docs/*.html  # Конкретные файлы

  role-paths:
    - path: /v1/api/hello
      roles: [USER, ADMIN]
#    - path: /v1/api/profile  # Доступно всем аутентифицированным
#      roles: [ ]

logging:
  level:
    io.netty: DEBUG