server:
  port: 8079
  servlet:
    context-path: "/v1/api"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password: redispassword

logging:
  level:
    root: INFO